### ISSUE TITLE
(BUG) Authorization reset policy on User / Hub / Organization is failing on ACC

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/cli#21]
**Describe the bug**
After deploying the latest master changes from the server to ACC env, authorization policy reset is failing for all types of entities (User, Hub, Organization)

**To Reproduce**
1. Run the command `npm run authorization-reset-all` against ACC env, some of the policy resets are failing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/153aa6b2-d4fb-410b-a8b3-0ec6fdbf26fd)

**Expected behavior**
Authorization policy reset succeeds for all entities.

**Comment by techsmyth** [comment]
Yes reproducible:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/614bf491-edd0-4a8e-86fd-70078ce1f323)

@Comoque1 can you get the raw authorization_policy.credentialRules field text for this particular user?

**Comment by techsmyth** [comment]
fyi - also the same issue for the hub that failed:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/706e9706-ab8b-46b8-a53a-d47723be65a9)
