### ISSUE TITLE
Profile refactoring - CLI, Client-lib, Populator

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/cli#28]
## Description

As a developer, I want to re-use as much code as possible
so that maintainability and extensibility are cheaper.

## Acceptance criteria

- [ ] Client-lib updated with the new API using Profiles
- [ ] Populator updated with the new API using Profiles
- [ ] CLI updated with the new API using Profiles

## Additional Context

Start with the populator

**Comment by techsmyth** [comment]
@valentinyanakiev this issue has to be in the current sprint to be able to release the new profile api
