### ISSUE TITLE
BUG: Sentry errors for inaccessible avatars (Acceptance) are making noise

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/cli#70]
## Description
Similar to what we did on PROD, we must replace the broken LinkedIn avatars on ACC.

## Acceptance criteria

- [x] Make sure there are no broken avatars on acceptance, causing noise in the Sentry logs.

**Comment by techsmyth** [comment]
@bobbykolev fyi - put some additional hopefully clarifying acceptance criteria

**Comment by bobbykolev** [comment]
I was moving this separately to fix the Sentry error logs. 
I'll extract the additional ACs in another ticket - https://github.com/alkem-io/cli/issues/69
@techsmyth FYI

**Comment by bobbykolev** [comment]
QA Notes:
There were **9** accounts with broken (LinkedIn) avatars on Acceptance.  
<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ebdda8094b3fa4be38ca300e70ac14aaaa58182/image.png" alt="image.png" />

All were fixed - repleaced with defalut ones (hosted on Alkemio). _Inaccessible Avatars: 0_
